[tool.poetry]
name = "master_thesis"
description = "A project for finding hidden shortcuts in 3D medical images"
version = "0.1.0"
authors = ["Max Andreas de Visser", "Bianca Pedersen"]
readme = "README.md"
packages = [{ include = "poetry_demo" }]

[tool.poetry.dependencies]
python = "^3.11"
pydicom = "^2.4.4"           # for reading DICOM files
ipykernel = "^6.29.5"
numpy = "^2.1.0"
pandas = "^2.2.2"
seaborn = "^0.13.2"
torch = "^2.4.0"
torchvision = "^0.19.0"
tqdm = "^4.66.5"
fiftyone = "^0.25.0"         # UI tool for inspecting images, labels and predictions
xlrd = "^2.0.1"              # Required for pandas to read excel files
pylidc = "^0.2.3"            # Package for LIDC-IDRI dataset
python-dotenv = "^1.0.1"
opencv-python = "^4.10.0.84"
pyqt6 = "^6.7.1"             # Required for itkwidgets (do not remember why it is needed)
scipy = "^1.14.1"
ruff = "^0.6.4"
wandb = "^0.18.1"
mypy = "^1.11.2"

[tool.poetry.group.medvis.dependencies]
streamlit = "^1.38.0"
streamlit-lottie = "^0.0.5"
requests = "^2.32.3"
itkwidgets = "^0.32.6"
pytest-shutil = "^1.7.0"
glob2 = "^0.7"
vtk = "^9.3.1"              # this is for reading nifti files (we need to read DICOM files)
plotly = "^5.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
