[tool.poetry]
name = "master_thesis"
description = "A project for finding hidden shortcuts in 3D medical images"
version = "0.1.0"
authors = ["Max Andreas de Visser", "Bianca Pedersen"]
readme = "README.md"
packages = [{ include = "poetry_demo" }]

[tool.poetry.dependencies]
python = "^3.11"
pydicom = "^2.4.4"
matplotlib = "3.5.2"
ipykernel = "^6.29.5"
numpy = "^2.1.0"
pandas = "^2.2.2"
seaborn = "^0.13.2"
torch = "^2.4.0"
torchvision = "^0.19.0"
tqdm = "^4.66.5"
fiftyone = "^0.25.0"
ipywidgets = ">=8,<9"
xlrd = "^2.0.1"         # Required for pandas to read excel files
pylidc = "^0.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
